### ISSUE TITLE
Separate severity for no-unused-declaration types

### ISSUE THREAD

**Issue by Nxt3** [cartant/tslint-etc#16]
I was hoping to set the `no-unused-declaration` severity for `imports` to be `error` but for `declarations` to be `warning`. Is something like that possible?

**Comment by cartant** [comment]
Not ATM.

Within a rule, failures are just reported with a location and a message. The severity is applied at the rule level in the config.

I did add configuration for the rule a while ago, so that you could run it for only imports, only declarations, or both - as someone was using it in a clean-up-imports script.

The best you could do, right now, would be to make two passes. That is run TSLint twice.

Soon, I'll be converting these rules - and the ones in `rxjs-tslint-rules` - to ESLint. At that stage, I might split this rule into two, but it's not something I really want to do right now. Especially as ESLint is the way forward for linting TypeScript.

**Comment by Nxt3** [comment]
Okay, no worries. Thanks for the swift response. :)
