### ISSUE TITLE
no-unused-declaration fixer doesn't work

### ISSUE THREAD

**Issue by Hotell** [cartant/tslint-etc#5]
running `tslint --fix` throws instead of removing unused declarations

```sh
"tslint": "5.11.0",
```

![image](https://user-images.githubusercontent.com/1223799/44655104-459f9200-a9f4-11e8-87e2-42e6ee94b419.png)

**Comment by cartant** [comment]
Pretty sure I did this by design and the fixer removes only unused import declarations. Otherwise, there is potential for it to remove code that cannot be easily replaced. If you were to spend some minutes writing something only to have it disappear, it could be somewhat upsetting.

I thought removing any and all unused declarations could be too catastrophic. I have vague memories of mentioning this, but it's not in the README. I guess it was in a Twitter conversation. Or something.

I guess an option could be added for those who like to live dangerously.

**Comment by cartant** [comment]
Yeah. It was in [a tweet](https://twitter.com/ncjamieson/status/993224067682521088). I'll mention it in the README.

**Comment by Hotell** [comment]
Valid points! cheers dude. 

I'll keep this open, you can close it when you update the docs WDYT ?

**Comment by cartant** [comment]
Yep. Leave it open, please. I'll update the README.

**Comment by cartant** [comment]
Done.
